[package]
name = "clean_histfile"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = "symbols"
panic = "abort"

# [target.x86_64-unknown-linux-gnu]
# rustflags = ["-C", "prefer-dynamic"]
