name: Cross Compile and Release

on:
  push:
    tags:
      - 'v*'  # 如 v0.1.0

jobs:
  build:
    name: Cross Compile for Linux targets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install cross
      uses: taiki-e/install-action@v2
      with:
        tool: cross

    - name: Build x86_64-unknown-linux-gnu
      run: cross build --release --target x86_64-unknown-linux-gnu

    - name: Build aarch64-unknown-linux-gnu
      run: cross build --release --target aarch64-unknown-linux-gnu

    - name: Rename binaries
      run: |
        mkdir dist
        cp target/x86_64-unknown-linux-gnu/release/clean_histfile dist/clean_histfile-x86_64
        cp target/aarch64-unknown-linux-gnu/release/clean_histfile dist/clean_histfile-aarch64

    - name: Upload binaries and generate release notes
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        files: |
          dist/clean_histfile-x86_64
          dist/clean_histfile-aarch64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
